language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install: pip install -r requirements/dev.txt
script:
- flake8 --max-complexity 12 .
- pylint --rcfile .pylintrc *.py settings urls apps libs || exit 0