language: python
python:
- '2.7'
- '3.4'
- '3.5'
install: pip install -r requirements/dev.txt
script:
- flake8 --max-complexity 12 .
after_success:
- pylint --rcfile .pylintrc *.py settings urls apps libs || exit 0
notifications:
  slack:
    secure: PKiHP5sTDfNbzhUQKdKcfbZmRTEbaKURDkuIrDKa0cQMGNTLtY7xJBJ2hCN5Iv5DHCjjo4VYe/eiQp1gACeq25aCinF9oP8gJG5X8nHkVpYg6jA5lXHkO8/jpEjdxRLhtrZ+kqUMKx3eAdfFN3YJqOw314GG42NjToK6jdLUods=
